#!/bin/env sh

## DOWNLOADING FONT
curl -o /tmp/JetBrainsMono.zip -L https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/JetBrainsMono.zip

unzip /tmp/JetBrainsMono.zip -d ~/.local/share/fonts/

fc-cache -vf ~/.local/share/fonts/

## INSTALLING BASIC SOFTWARE
sudo dnf up && sudo dnf in emacs-pgtk qutebrowser

## COPYING CONFIG FILES
cp ~/devdots/emacs/* ~/.emacs.d
cp ~/devdots/sway/* ~/.config/sway/

