#!/bin/env sh

echo "DEVDOTS: COPYING CONFIG FILES"
mkdir -p ~/.emacs.d
cp ~/devdots/emacs/* ~/.emacs.d

mkdir -p ~/.config/sway
cp ~/devdots/sway/* ~/.config/sway/

mkdir -p ~/.config/qutebrowser/styles
cp ~/devdots/qutebrowser/*.py ~/.config/qutebrowser/
cp ~/devdots/qutebrowser/*.css ~/.config/qutebrowser/styles

if [ ! -f ~/.local/share/fonts/JetBrainsMonoNerdFont-Regular.ttf ]; then
    echo "DEVDOTS: DOWNLOADING FONT"
    
    curl -o /tmp/JetBrainsMono.zip -L https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/JetBrainsMono.zip

    unzip /tmp/JetBrainsMono.zip -d ~/.local/share/fonts/

    fc-cache -vf ~/.local/share/fonts/
fi

if [ ! -f /usr/bin/emacs ]; then
    echo "DEVDOTS: INSTALLING BASIC SOFTWARE"
    
    sudo dnf up && sudo dnf in emacs-pgtk qutebrowser
fi
